export { Header } from './header/Header';
export { MainBanner } from './MainBanner';
export { LineNotice } from './LineNotice';
export { NewRewards } from './NewRewards';
export { Reserve } from './Reserve';
export { Favorite } from './Favorite';
export { Magazine } from './Magazine';
export { Store } from './Store';
export { Footer } from './footer/Footer';
