export { Header } from './header/Header';
export { MainBanner } from './mainBanner/MainBanner';
export { LineNotice } from './lineNotice/LineNotice';
export { NewRewards } from './newRewards/NewRewards';
export { Reserve } from './reserve/Reserve';
export { Favorite } from './favorite/Favorite';
export { Magazine } from './magazine/Magazine';
export { Store } from './store/Store';
export { Footer } from './footer/Footer';
